import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "It's hellomyzn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative min-h-screen overflow-x-hidden font-thin">
        {/* 固定ヘッダー：右上にナビゲーション */}
        <header className="fixed top-0 z-50 bg-white left-0 sm:left-auto sm:right-0 border-b border-r sm:border-l sm:border-r-0">
          <nav className="flex">
            {/* Home */}
            <div className="p-3 border-r">
              <Link href="/" className="px-2 py-1 w-20 text-center highlight">
                Home
              </Link>
            </div>
            {/* Posts */}
            <div className="p-3 border-r">
              <Link href="/posts" className=" px-2 py-1 w-20 text-center">
                Posts
              </Link>
            </div>
            {/* About */}
            <div className="p-3">
              <Link href="/about" className="px-2 py-1 w-20 text-center">
                About
              </Link>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
